### ISSUE TITLE
Idea: Canocial file names 

### ISSUE THREAD

**Issue by gehaxelt** [JamieFarrelly/Popular-Site-Subdomains#1]
Hi,
I'd suggest to use a consistent naming scheme. For example `domain.tld.txt` or so. 

Maybe we could even use directories?

```
$>tree . 
.
├── facebook.com
│   ├── 2015-10-10.txt
│   └── 2016-09-17.txt
└── google.de
    ├── 2013-01-01.txt
    └── 2016-10-01.txt

2 directories, 4 files
```

That way one could use "git diff" and so on...

**Comment by JamieFarrelly** [comment]
Yeah it would be better to have at least something like Facebook.com.txt. I added Facebook's subdomains first and it includes some subdomains that are on the fb.com domain, but having different files for each would be nicer I suppose.

Folders might be a bit much for the moment, want to keep things simple :+1:

**Comment by JamieFarrelly** [comment]
Each file now includes the full domain. Eg. Facebook.com.txt, Facebook.co.uk.txt

I'll close this for now, thanks.
