### ISSUE TITLE
Does it make sense to exclude www.?

### ISSUE THREAD

**Issue by aidanbh** [JamieFarrelly/Popular-Site-Subdomains#13]
Unlike http://, www. is not a prefix but a subdomain itself. While it often redirects to the root domain or vice versa, they sometimes do point to different hosts. Also many sites use ww2., ww3., etc. - how does this rule affect them?

**Comment by JamieFarrelly** [comment]
Yeah you're right, I quickly wrote up the readme a while back and had this as a rule - I'll remove it now. Thanks.

**Comment by JamieFarrelly** [comment]
At some stage the files need to be updated to include www., but for now it's okay.
